### ISSUE TITLE
Feature: TTL or Auto-expiration

### ISSUE THREAD

**Issue by beeftornado** [alekseykulikov/treo#15]
I have some boilerplate code I have to use around my store access to refresh the data after a period of time. Thought it would be nice if it was implemented at a library level. `addStore()` could accept a `ttl` parameter, which would be a duration. On `put`'s, an expiration time can be generated and on `get`'s, the expiration time can be checked. If the data has expired it can call a 'generator' function (a callback) to regenerate the data. This is basically what I do now to refresh the cache every day.

**Comment by alekseykulikov** [comment]
I hope someone will create a plugin for this idea eventually, close for now
