### ISSUE TITLE
Problem in Safari 7.1 and 8

### ISSUE THREAD

**Issue by beeftornado** [alekseykulikov/treo#17]
Safari added indexedDB, but it seems broken and since it actually exists, Treo never falls back to websql (if one opted to use the plugin). According to some investigation done by pouchdb guys, Safari may not always fire the `onupgradeneeded` event and thus for new databases, the stores will never be created. This throws an exception.
https://github.com/pouchdb/pouchdb/issues/2533

Maybe in the websql plugin we can activate it using the hack they chose to do...
https://github.com/pouchdb/pouchdb/commit/2a2e722b06d98a8122c751361b7e80b1e066c721

I'm going to try it out locally.

**Comment by alekseykulikov** [comment]
Closes by https://github.com/unkillbob/treo/commit/ec157c6c16714436563ac04e431c55eda7b751be
