### ISSUE TITLE
Any easy way to create multi-field indexes, not just single field?

### ISSUE THREAD

**Issue by mariusk** [alekseykulikov/treo#24]

**Comment by alekseykulikov** [comment]
Treo supports `multi` as a part of `addIndex`: https://github.com/alekseykulikov/treo#schemaaddindexname-field-opts

```js
schema = treo.schema()
    .version(1)
      .addStore('magazines', { key: 'id' })
      .addIndex('byWords', 'words', { multi: true });
```

Is it what you need?

**Comment by mariusk** [comment]
I do not think so. I'm under the (possibly wrong) impression that indexeddb allows indexes based on multiple field values, not just a named array field.

**Comment by alekseykulikov** [comment]
Ah, probably you mean something like: http://stackoverflow.com/a/16503172

```js
schema.addIndex('compoundIndex', ['field1', 'field2']);
```

Currently treo will not allow to do this, because it expects string as a key field: https://github.com/alekseykulikov/treo/blob/master/lib/schema.js#L90
Also probably ranges will not work too.

I will mark it as a feature for next release.

**Comment by mariusk** [comment]
Another thing to add to the feature list might be an easy way to call `.all` on a cursor or similar, to iterate by a certain index. Alternatively, add interfaces (or document) how to access the underlying cursors to do it.

**Comment by alekseykulikov** [comment]
Yes, support of ranges in `store.all` could be a good addition.
Internal `store.cursor` is also available, but has weak docs. So far as example you can check: https://github.com/alekseykulikov/treo/blob/master/examples/find-in-plugin.js

**Comment by robertfall** [comment]
We've just run into this issue. Is there a way to drop down to raw indexeddb to add the index with multiple fields until it's been added to treo? :confused:

**Comment by alekseykulikov** [comment]
treo@0.5.0 adds support for this functionality.

**Comment by lukerandall** [comment]
Thanks for the quick response. Much appreciated!

**Comment by robertfall** [comment]
Indeed! Didn't expect this to land so soon. Thanks for your work! :+1:

**Comment by alekseykulikov** [comment]
You're welcome, guys!
