### ISSUE TITLE
Fails on iOS 8 when pinned to homepage

### ISSUE THREAD

**Issue by mariusk** [alekseykulikov/treo#25]
Here's the error: `"null is not an object (evaluating 'indexedDB().open')"`

It seems this is a known bug in iOS 8, and a proper workaround might be to activate the websql shim if `indexedDB()` evaluates to null.

**Comment by mariusk** [comment]
So on iOS 8.1.3 the userAgent (when pinned) is: `Mozilla/5.0 (iPad; CPU OS 8_1_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12B466`.

Inside `indexeddb-shim.js` there is a check for `/Safari/`, which obviously does not trigger for this user agent. Adding `/AppleWebKit.*Mobile/` or similar in an extra clause triggers the websql shim workaround for pinned apps as well. With this change it seems to work fine on iOS 8 as well.

**Comment by mariusk** [comment]
Made a PR with the suggested change here https://github.com/alekseykulikov/treo/pull/26.

**Comment by alekseykulikov** [comment]
Thank you for PR! treo@0.4.3 is released https://github.com/alekseykulikov/treo/blob/master/History.md#043--2015-03-09
